spring:
  application:
    name: blog-user
  datasource:
    url: jdbc:mysql://47.101.221.215:3306/blog?characterEncoding=UTF8
    username: root
    password: rootblog
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 47.101.221.215
  redis:
    host: 47.101.221.215
server:
  port: 8502
